import os
import json
import logging

DUMP_FILE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "rabbit_journals_dump.json")

def fetch_rabbit_journals(token, log_callback=print):
    """Loads journal data from the local file cache generated by the automated browser script."""
    if log_callback is None:
        log_callback = logging.info

    log_callback("Reading journal data from your browser session cache...")
    
    if os.path.exists(DUMP_FILE):
        try:
            with open(DUMP_FILE, "r", encoding="utf-8") as f:
                journals = json.load(f)
                if isinstance(journals, list) and len(journals) > 0:
                    log_callback(f"Successfully loaded {len(journals)} journal entries from local cache storage.")
                    return journals
        except Exception as e:
            log_callback(f"Cache access error: {str(e)}")
            
    log_callback("⚠️ No journals found in the local cache. Please click 'Auto-Fetch Token' first to download your data.")
    return []
